language: go
go: 
 - 1.1
 - 1.2
 - 1.3
 - 1.4
 - release
 - tip

env:
  - $PATHZZ=$PATH:$GOPATH/bin

before_install:
  - go install -race std
  - go get -v golang.org/x/tools/cmd/cover
  - go get github.com/kr/godep
  - export PATH=$HOME/gopath/bin:$PATH
  - export GOPATH=`godep path`:$GOPATH

install:
  - godep restore

script:
  - go test
  - test -z "$(go fmt ./...)"